### ISSUE TITLE
提个建议~

### ISSUE THREAD

**Issue by coco86775005** [lizhangqu/CorePage#2]
corepage的fragment管理还是比较完整的，最大限度的模拟了Activity的启动方式，但是配置json文件的方式不是太好，特别是配置的page需要完整的路径包名，如果代码fragment重构，或者挪动了地方，配置文件就需要手动再改，建议可以参考开源框架Arouter的类似跳转方式，给每个Fragmentd定义一个与路径无关的名字，根据注解去动态查找加载类，这样配置起来更灵活易用。

**Comment by lizhangqu** [comment]
最开始是只支持注解的，后来注解的功能被移除了改为json了，如果需要，可自行添加
